// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlikaOglasi.Models;

namespace SlikaOglasi.Migrations
{
    [DbContext(typeof(OglasiContext))]
    [Migration("20190729160249_Prva")]
    partial class Prva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SlikaOglasi.Models.Oglasi", b =>
                {
                    b.Property<int>("OglasiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cena");

                    b.Property<byte[]>("FajlSlike");

                    b.Property<int>("Godiste")
                        .HasMaxLength(4);

                    b.Property<string>("Gorivo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Karoserija")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Motor")
                        .HasMaxLength(6);

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Snaga_Ks")
                        .HasMaxLength(3);

                    b.Property<string>("TipFajla")
                        .HasMaxLength(20);

                    b.HasKey("OglasiId");

                    b.ToTable("Oglasi");
                });
#pragma warning restore 612, 618
        }
    }
}
