// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlikaOglasi.Models;

namespace SlikaOglasi.Migrations
{
    [DbContext(typeof(OglasiContext))]
    partial class OglasiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SlikaOglasi.Models.Kontakt", b =>
                {
                    b.Property<string>("Ime")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Poruka")
                        .IsRequired();

                    b.Property<string>("Telefon")
                        .IsRequired();

                    b.HasKey("Ime");

                    b.ToTable("Kontak");
                });

            modelBuilder.Entity("SlikaOglasi.Models.Oglasi", b =>
                {
                    b.Property<int>("OglasiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cena");

                    b.Property<byte[]>("FajlSlike");

                    b.Property<int>("Godiste");

                    b.Property<string>("Gorivo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Karoserija")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Motor");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Snaga_Ks");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("OglasiId");

                    b.ToTable("Oglasi");
                });
#pragma warning restore 612, 618
        }
    }
}
